#!/bin/bash

LISTOFDOMAINS="officeapps.live.com
officeclient.microsoft.com"

HOSTSFILE="hosts.list"

rm -f "${HOSTSFILE}"
cat <<EOL > "${HOSTSFILE}"
# This is autogenerated by a script
# This list may contain incorrect entries and can destroy the entire local DNS Resolution

EOL

for LISTOFDOMAIN in ${LISTOFDOMAINS}; do
    echo "# This list contain most subdomains of ${LISTOFDOMAIN}" >> "${HOSTSFILE}"

    OUTPUTS=$(curl -s "https://crt.sh/?q=%25.${LISTOFDOMAIN}&output=json" \
        | jq -r '.[].common_name' \
        | grep -v '^\*\.' \
        | sort -u \
        | grep "${LISTOFDOMAIN}")

    for OUTPUT in ${OUTPUTS}; do
        echo "0.0.0.0 ${OUTPUT}" >> "${HOSTSFILE}"
    done

    echo "" >> "${HOSTSFILE}"
done
